### ISSUE TITLE
Misbehaviour of key event

### ISSUE THREAD

**Issue by Benature** [shuowu/yi-note#12]
1. the enter event maps to `save note` but also add an enter into note text.
eg: `|` indicates the cursor position when I enter
```
test a |video.
```
turns into 
```
test a 
video.
```
which is not I want.

Hope yi-note can, for example, discriminate <kbd>enter</kbd> and <kbd>enter</kbd> with decorate key, like <kbd>shift+enter</kbd> for `save note` and `add an enter into note text`.

2. On some websites, like <https://v.qq.com/>, when I click blank(<kbd> </kbd>), it will pause the video too.

**Comment by shuowu** [comment]
@Benature `shift+enter` should be supported in YiNote editor. Also to view notes with proper lin break, you may need to expand note.

To answer your second question
> On some websites, like https://v.qq.com/, when I click blank(), it will pause the video too.

I assume you mean press space key on the keyboard to pause the video. 
From the design perspective, I tried to avoid hotkeys as much as possible, as I want YiNote to serve different platforms, but different platforms may have varied ways of implementing hotkeys. So the best way to avoid key confliction is not to implement it :)

**Comment by shuowu** [comment]
Linked to wrong PR... Reopen

**Comment by shuowu** [comment]
Close this issue as in the current implementation is `enter` for saving, `shift + enter` for adding a new line.

@Benature Please reopen this ticket if you have further questions.
