### ISSUE TITLE
Function buttons missing if you add note by clicking confirm instead of tap enter

### ISSUE THREAD

**Issue by kerryChen95** [shuowu/yi-note#24]
![image](https://user-images.githubusercontent.com/1589388/82751023-f237bf00-9de6-11ea-896d-3accb0d1deea.png)

If you add note by clicking save instead of tap enter, as above, then panel look like below, function buttons missing!
![image](https://user-images.githubusercontent.com/1589388/82750924-527a3100-9de6-11ea-9d03-dafff15c7f4d.png)

Hope for fixing the bug early, thanks : )

**Comment by shuowu** [comment]
@kerryChen95 From the screenshots above, looks like you are also missing `Settings` button at the bottom of the panel, can you please check if you have the latest published version? 
The latest version in the chrome web store is `v1.1.0`

**Comment by shuowu** [comment]
@kerryChen95 Feel free to reopen this issue with version information if the bug still exist.
