### ISSUE TITLE
Exported PDF timestamps different to original timestamps

### ISSUE THREAD

**Issue by GlennHodnett** [shuowu/yi-note#29]
[Stellor v Norbury Cup.pdf](https://github.com/shuowu/yi-note/files/4677369/Stellor.v.Norbury.Cup.pdf)
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

- Extension Version:
- Browser:

**Comment by shuowu** [comment]
@GlennHodnett Can you provide more details of this issue? I tried to generate pdf from the extension, but cannot reproduce the issue. It would be helpful if you can share a screenshot of timestamps in your extension, and show what's the difference with time generated in PDF.

**Comment by GlennHodnett** [comment]
Hi, first of all it's a fantastic Chrome extension thanks. When I click on
the hyperlink time in the PDF file say at 0:38 it takes me to 1hr 6 mins
into the video. Also can the time be manually adjusted so say if a goal is
scored I can set it to play 10/15 secs before the event

**Comment by shuowu** [comment]
@GlennHodnett Option for set jump back time is tracked here. #30 

For this issue, it looks like auto-seek is broken for pdf link, I'll take a look.

**Comment by GlennHodnett** [comment]
Thank you :)

**Comment by shuowu** [comment]
The issue will be fixed in new release v1.3.0.
