### ISSUE TITLE
Option for jump several seconds back when play video at noted timestamp

### ISSUE THREAD

**Issue by shuowu** [shuowu/yi-note#30]
Option should be provided in the Settings page.

**Comment by GlennHodnett** [comment]
Cant seem to find it in the settings to alter the seconds

**Comment by shuowu** [comment]
@GlennHodnett The ticket here is created to track the issue. It will be fixed in the next release, which should be v1.3.0

**Comment by shuowu** [comment]
The issue will be fixed in new release v1.3.0.
