### ISSUE TITLE
Export to One Note functionality is broken

### ISSUE THREAD

**Issue by zhenwei2972** [shuowu/yi-note#40]
**Describe the bug**
Got an error message when attempting to export to one note

**To Reproduce**
Authenticate with microsoft sign-in
attempt to send to one note
error occurs

**Expected behavior**
export succeeds

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - Latest

First time user

----
Would also like to thank you for making this amazing app!

**Comment by shuowu** [comment]
@zhenwei2972 Thanks for reporting this issue. I tried the latest version of YiNote from chrome web store, but cannot reproduce the issue. Wondering are you build the extension from the code? If that's the case, you also need to set up your own OAuth2 application on MS Azure to make sure it allows the callback URL. 

Also, it would be helpful to provide your current extension version if you installed it from the chrome web store.

**Comment by zhenwei2972** [comment]
current installed version is v1.3.0, I am not building extension from code.
I am able to reproduce it anytime when trying to send notes to one not.
I suspect something wrong with the authentication? Not quite sure how I can re-login to Microsoft, maybe backup, uninstall and re-install?

**Comment by shuowu** [comment]
Thanks for the detailed information, I’ll investigate on this issue. Meanwhile, if you are familiar with how to inspect extension’s storage(not browser localstorage), you can try to clear the access token of onenote, then try again.

**Comment by zhenwei2972** [comment]
thank you for the quick reply, let me know how I can help, with any diagnostic tests, I will try to install on my brother's computer too and see if i can reproduce. It is a great extension, will be sharing with all my friends!

**Comment by shuowu** [comment]
@zhenwei2972 
Firstly, send notes to OneNote is going through OAuth2 process and then call remote MS graph services, so I don't think deactivate other extensions can help.  Just want to make sure you have an OneNote account first, YiNote only can send notes to the existing OneNote account, but not create an account with MS account.

Then, YiNote is logging error in browser's dev console
https://github.com/shuowu/yi-note/blob/master/extension/src/ui/containers/VideoNotesView/SendToServices/index.js#L60
Can you please inspect the page you take notes and check if there are any error messages prefixed with `yi-note` in your browser's console? Please share the error log if you can find any.

Also, you can try to remove your OneNote accessToken in storage, then try again. You can follow the steps below:
1. go to `chrome://extensions` from browser's address bar
2. find `YiNote`, then click on inspect views background page
3. Run `chrome.storage.local.set({onenote: {}})` in background page's devTool console to clear oneNote meta data.

Let me know if any of these suggestions can help get more info on the issue. Thanks!

**Comment by zhenwei2972** [comment]
I am unable to see any yi-note error logs on the console, even upon re-authenticating then sending to onenote.
Upon going to inspect views background page, there are multiple logs though, am attaching them in a screen shot here. chrome.storage.local.ste({onenote: {}}) seems to return undefined not quite sure why. 
![image](https://user-images.githubusercontent.com/7851060/84734867-ab4b7c80-afd4-11ea-999b-f7cfaf1ba759.png)

Thank you for investigating, it is a minor issue no rush actually, I am using the built in notes viewer which works well, just wanted to report the OneNote issue so that you are aware. 

I have a seperate more urgent issue which pertains to my use case on coursera, when going to next video via next button in coursera, the YiNote extension will not be able to "hook" properly to the new video and will fail to function, i.e only can put time stamp at 0.00, then unable to submit new notes. A simple refresh F5 fixes this, not really a big issue just letting you know, not sure if u can add in a auto-refresh for the extension when next video is played to fix this issue.

**Comment by shuowu** [comment]
@zhenwei2972 #42 has been created to track the Coursera issue.

Per the OneNote issue,  from the error message, it looks like the extension failed to make proper requests after one access token gets invalid. Wondering have you ever successfully send notes to Onenote, I suspect it's caused by a bug in accessToken renew logic. Also are you able to send notes after running the script in the console?

Btw, the `undefined` response is desired, the command just reset OneNote metadata in storage, and the return value of that script is `undefined`.

**Comment by zhenwei2972** [comment]
okay got it, thank you! will look forward to the release!

**Comment by shuowu** [comment]
v1.4.0 has been published in chrome web store, please update the extension and verify if the issue has been fixed.

**Comment by zhenwei2972** [comment]
Hi would like to verify that this has indeed been fixed! thank you!
