### ISSUE TITLE
Share and export not visible with lots of text 

### ISSUE THREAD

**Issue by DStar1** [shuowu/yi-note#41]
**Describe the bug**
When there is a lot of text in a note entry, there is an overflow, but no ability to scroll in the x direction, so no ability to see the export or share buttons.

**To Reproduce**
Type a lot of text in an entry for a note and behavior is reproducible.

**Expected behavior**
Should show share and export always.

**Screenshots**
![unnamed](https://user-images.githubusercontent.com/32213063/84703782-a35eee80-af7a-11ea-9df5-56e8f2177ab1.jpg)
![unnamed (1)](https://user-images.githubusercontent.com/32213063/84703804-ac4fc000-af7a-11ea-9c5c-45a6a792258a.jpg)

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina
 - Browser chrome
 - Version newest

**Additional context**
I sent you an email with a video showing the problem as well. As well as my hacky solution with overflow-x. [harrisonfsmith95]

**Comment by shuowu** [comment]
v1.4.0 has been published in chrome web store, please update the extension and verify if the issue has been fixed.
