### ISSUE TITLE
Why Lost all notes after upgraded to YiNote v1.3.0?How can I find these note!!!?

### ISSUE THREAD

**Issue by vicvan1990** [shuowu/yi-note#43]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shuowu** [comment]
@vicvan1990 If chrome upgrades the extension automatically, migration script should be able to transform the notes to the newer format and also download two backup files, files name should be `yinote_storage_local_0.6.4.json` and `yinote_storage_sync_0.6.4.json`. Please also see [MIGRATION GUIDER](https://github.com/shuowu/yi-note/blob/master/MIGRATING.md) for more information.

But if you uninstalled the extension manually, then installed v1.3.0 afterward. Unfortunately, your data most probably got erased during uninstallation. [FAQ](https://github.com/shuowu/yi-note#faqs)

Let me know if you have more questions. Thanks

**Comment by vicvan1990** [comment]
@shuowu 
1).The extension automatically upgraded by chrome;
2).I can't find the files called  yinote_storage_local_0.6.4.json  and  yinote_storage_sync_0.6.4.json 
 by searching my Mac;Could you tell me  the path of the two documents?
3).There are almost 80 bookmarks with notes in the old version, but now it only keeps the link with no notes of these bookmarks (only one bookmark with entire notes)
Thank you for your help!

**Comment by shuowu** [comment]
Sorry, I miss-spelled the file name, it should be `storage_local_0.6.4.json` and `storage_sync_0.6.4.json`. And by default chrome should download them in your /Downloads folder.

Another thing you can try is to check data in your extension storage by
1. go to `chrome://extensions` from chrome address bar
2. find YiNote extension, then open `background` page
3. In the popup chrome Devtool console, run script `chrome.storage.local.get(d => console.log(d))` and `chrome.storage.sync.get(d => console.log(d))` to check the data for your extension.

Hopefully, you can find your backup files, then I'll investigate on how to recover your notes. Sorry for the bug introduced with the version upgrade.

**Comment by vicvan1990** [comment]
<img width="752" alt="Xnip2020-06-19_08-52-12" src="https://user-images.githubusercontent.com/52686483/85085719-34e48f80-b20b-11ea-98bc-0ebc98d3b617.png">

**Comment by vicvan1990** [comment]
@shuowu 
1.Still can‘t find these two files（storage_local_0.6.4.json and storage_sync_0.6.4.json）by searching my MacBook.
2.I ran the scripts , it only show the links of the websites but the notes are all lost.
<img width="752" alt="Xnip2020-06-19_09-10-09" src="https://user-images.githubusercontent.com/52686483/85086291-c30d4580-b20c-11ea-944e-5249fb4efd6a.png">
I need your help!Thank you so much.

**Comment by shuowu** [comment]
Can you try check downloads files from `chrome://downloads`, there should be at least a record there, even you deleted files from the disk.
I should backup old data in a better way... sorry about that

**Comment by vicvan1990** [comment]
@shuowu 
Only find out json document after 6/16/2020 which downloaded manually by myself and it still lost.Tried all the methods, are there any other methods to find out my notes ?Thank you !
<img width="1051" alt="Xnip2020-06-19_10-49-30" src="https://user-images.githubusercontent.com/52686483/85091863-079fdd80-b21b-11ea-986f-c1173a36949a.png">

**Comment by vicvan1990** [comment]
All the 80 bookmarks still keeps, just lost the notes and only one bookmarks with all the notes, which is very  confused.

**Comment by shuowu** [comment]
YiNote will try to migrate the old data when upgrading from 0.6.4, and then back up old data in JSON files in case the data migration failed.
https://github.com/shuowu/yi-note/blob/master/extension/src/background/migrations/0.6.4.js#L77
But looks like there is a bug in the migration script, and it also failed to download backups in your case somehow (probably because chrome's ask permission for downloading has been turned on in your browser ) ... 

I should keep the backup data in storage by some approach instead of downloading it as the backups. I would suggest periodically backup your notes from options page as YiNote currently can only store data in the browser's storage, which might be erased by accident (like migration failure or deletion of the extension).

Sorry again for the troubles introduced in the new updates.

**Comment by shuowu** [comment]
@vicvan1990 Sorry again about the data lost. I have created a feature ticket ( #46 ) to add auto backup strategy into YiNote. Hopefully, it can help on your future usage.
