### ISSUE TITLE
Long word is wrapped into separate lines.

### ISSUE THREAD

**Issue by Faris999** [shuowu/yi-note#47]
**Describe the bug**
A long word is wrapped into separate lines where it should be just put in one line.

**To Reproduce**
Type a long word

**Expected behavior**
It should be on just one line of it fits on its own.

**Screenshots**
Current Behavior:
![image](https://user-images.githubusercontent.com/28823677/87114029-c50d7600-c299-11ea-955c-e5051d85df0b.png)
Expected Behavior:
![image](https://user-images.githubusercontent.com/28823677/87114079-e2424480-c299-11ea-983f-70e2a993f066.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83

I think it can be fixed by adding the `word-break: break-word` CSS style into the `textarea`.

**Comment by shuowu** [comment]
@Faris999 Thanks for reporting the issue. I'll fix it in the next update.

**Comment by shuowu** [comment]
@Faris999 Fix will be available in v1.5.1

**Comment by Faris999** [comment]
Thanks!
