### ISSUE TITLE
Not creating PDF

### ISSUE THREAD

**Issue by mbairdgithub** [shuowu/yi-note#48]
When I click "Create PDF" nothing happens.

When I click create Google Doc it does stuff. 

I need to download and share my notes with a client via pdf

Thank you!

**Comment by shuowu** [comment]
@mbairdgithub I checked the latest version 1.5.0. Looks like it can generate the pdf and download it without issues. 

Several things you can try:
1. make sure you have the latest version upgraded in chrome.
2. check in `chrome://settings` to see if there are any specific settings to block file download.
3. inspect the options page, see if there is any error log in dev console. (right-click the webpage, then click `Inspect` to open browser dev console)

**Comment by mbairdgithub** [comment]
I'm running on Chromebook 

Your Chromebook is up to date
Version 83.0.4103.119 (Official Build) (64-bit)

YiNote v1.5.0

**Comment by mbairdgithub** [comment]
Also tried on PC and same thing. V 1.5.0 of YiNote

**Comment by mbairdgithub** [comment]
![Screenshot 2020-07-10 at 11 18 54 AM](https://user-images.githubusercontent.com/68121284/87181265-3f8cc480-c29f-11ea-9689-7299a97c7526.png)

**Comment by shuowu** [comment]
Can you right-click on this page, then click `Inspect` to see if there is any error log?

**Comment by shuowu** [comment]
And also check you downloads folder (I am sure the exact name for your OS), the file might be downloaded silently into the downloads folder.

**Comment by mbairdgithub** [comment]
DevTools failed to load SourceMap: Could not load content for chrome-extension://fhpgggnmdlmekfdpkdgeiccfkignhkdf/vendors/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://fhpgggnmdlmekfdpkdgeiccfkignhkdf/popper.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by shuowu** [comment]
> DevTools failed to load SourceMap: Could not load content for chrome-extension://fhpgggnmdlmekfdpkdgeiccfkignhkdf/vendors/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
> DevTools failed to load SourceMap: Could not load content for chrome-extension://fhpgggnmdlmekfdpkdgeiccfkignhkdf/popper.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

These errors should not matter.

**Comment by mbairdgithub** [comment]
Was able to download as .json Not sure what that is or what I can do with it.

**Comment by mbairdgithub** [comment]
Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at Object.H.splitTextToSize (options.js:35136)
    at PDFGenerator._callee$ (options.js:25681)
    at tryCatch (options.js:56794)
    at Generator.invoke [as _invoke] (options.js:57023)
    at Generator.prototype.<computed> [as next] (options.js:56846)
    at asyncGeneratorStep (options.js:2799)
    at _next (options.js:2821)

**Comment by shuowu** [comment]
The exported json file can be used as data backup, or share with others so they can import data to the extension. If the pdf button cannot work for you, one workaround can be send notes to OneNote or Evernote, then generate PDF from there. (print -> export as pdf)

**Comment by shuowu** [comment]
> Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
> at Object.H.splitTextToSize (options.js:35136)
> at PDFGenerator._callee$ (options.js:25681)
> at tryCatch (options.js:56794)
> at Generator.invoke [as _invoke] (options.js:57023)
> at Generator.prototype. [as next] (options.js:56846)
> at asyncGeneratorStep (options.js:2799)
> at _next (options.js:2821)

This error might be the issue, I'll look into it. Thanks for reporting the bug!

**Comment by mbairdgithub** [comment]
I love the idea of your app. Could be very helpful for me if I can make it work.

THANK YOU.

Stay Safe

**Comment by mbairdgithub** [comment]
Error when I tried sending to EverNote

[@yi-note/extension:options:containers:Page:Toolbar:index] ThriftException
invokeConsoleMethod @ options.js:350
options.js:350 [@yi-note/extension:options:containers:Page:Toolbar:index] ThriftException

**Comment by shuowu** [comment]
@mbairdgithub  can you do me a favor? Export the page you have issue with generating pdf from bookmarks page?

Steps:
1. click `Bookmarks` from left panel
2. choose `select bookmarks to export` from top right corner. Then select the page to export.
3. share the json file here or send to my email (wushuo2010@gmail.com)

> Error when I tried sending to EverNote
[@yi-note/extension:options:containers:Page:Toolbar:index] ThriftException
invokeConsoleMethod @ options.js:350
options.js:350 [@yi-note/extension:options:containers:Page:Toolbar:index] ThriftException

looks like last update breaks some features, sorry about that.. I'll make the fix.

**Comment by mbairdgithub** [comment]
Just emailed it to you

**Comment by mbairdgithub** [comment]
Any idea when I want to check back and try it again?

**Comment by shuowu** [comment]
> Any idea when I want to check back and try it again?

I'll update in this issue thread when there are any updates. You should be emailed with the update by GitHub.

**Comment by mbairdgithub** [comment]
Thank you!

**Comment by shuowu** [comment]
@mbairdgithub fix will be available in v1.5.1

**Comment by mbairdgithub** [comment]
When will that be available? Sorry I need to use this for a project? I
really need some idea of when to expect it.

THANK YOU
