### ISSUE TITLE
Title and link are taken from the first video that was played in that tab. 

### ISSUE THREAD

**Issue by tomasdore** [shuowu/yi-note#51]
Works perfectly for first video played: title and links are correct in the notes created. But any **further** videos played _in that tab_ then still use the **same** title and URL (from the first video) for their notes; so their notes therefore contain the wrong title and wrong links.

**Comment by tomasdore** [comment]
Sorry, I see that you have this in the FAQ. So maybe you are aware of this issue already. Perhaps the FAQ can mention that it also applies to the links (on the timecodes).

_"Why I bookmarked same title and thumbnail for different videos on Youtube?
Youtube don't update page metas, like title and thumbnails, when video changed in page. So reload page is needed to make sure YiNote can capture proper metadata for the video. YiNote also enabled settings in options page to enable auto reload when video change."_

**Comment by tomasdore** [comment]
But setting "Reload tab when url change" is not fixing the issue for me. I have to manually open a new tab for each new video. I am testing on https://www.youtube.com/watch?v=pNp8Qf20-sA&list=PLiaHhY2iBX9g6KIvZ_703G3KJXapKkNaF&index=10

**Comment by shuowu** [comment]
@tomasdore Did you also add domain ‘www.youtube.com’?

**Comment by tomasdore** [comment]
No, sorry, I am only seeing, or understanding this now:

 _Page domain, like www.youtube.com, need to be added when enable this setting. YiNote only applys reload behaviour to listed domains in the settings page._

Thanks for your response! Sorry for report with information you know about!
