### ISSUE TITLE
All Notes are set to 00:00 in timeline

### ISSUE THREAD

**Issue by GlennHodnett** [shuowu/yi-note#53]
When i enter a highlight it sets at 00:00 as opposed to where it should be in the timeline

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser (please complete the following information):**

**Additional context**

**Comment by shuowu** [comment]
@GlennHodnett Thanks for reporting this issue. A fix version (1.5.3) has been submitted for review, should be available in chrome web store in next 24hrs.

**Comment by GlennHodnett** [comment]
No problem, thank you
