### ISSUE TITLE
Maintain the structure from the markdown

### ISSUE THREAD

**Issue by tomasdore** [shuowu/yi-note#59]
**Is your feature request related to a problem? Please describe.**
I use Yi-Note to create notes, using Markdown. So I might use a header. Or make bullet points. This is good: it provides structure and it works, in that note. But then when I finish a playlist, I want to put my notes together, into a document that I can use to keep my knowledge. So I export the notes. But after export, I don't have the structure! No headings. Then it feels like using that Markdown is wasted effort.

**Describe the solution you'd like**
I would like to export to a format that kept the headings. I don't mind if I have to use something else, so if I export to Google docs, or Microsoft Word Online, it's perfect if it becomes a Google doc or Word doc, with the same structure: the headings and the bullet points.

**Describe alternatives you've considered**
But if I cannot have this perfect solution, then to export just raw markdown might be enough. For example, if sent to Google Docs, i would install a plugin for docs to allow me to read that markdown in the browser.

**Additional context**
An example is this playlist called "[imaginary numbers are real](https://www.youtube.com/playlist?list=PLiaHhY2iBX9g6KIvZ_703G3KJXapKkNaF)"
You can see that for a subject like this, after making notes on each video, it is natural to want to combine the notes.

**Comment by shuowu** [comment]
Good idea! I'll add a setting to retain markdowns when export. 
During development, i found its too much work to support markdown in all export formats (ms oneonte probably can be supported without too much effort), but still think it's helpful to have it in the editor. 

I am also planning to turn yinote into a web app with simple cloud support. Then viewing styled notes cross different devices would be available just via the app.

**Comment by marciovenicio** [comment]
I have the same problem. Including, I started using your app because of it. I intend to export the notes to Obsidian, so, it is crucial that works.

**Comment by DryIce1** [comment]
I would love this feature too. 

is it possible to export the MD formatting to a downloadable plain text / MD file? 

thanks

**Comment by filipgoc** [comment]
Another 👍  Yes! Markdown export. 

- One option is to allow copying the markdown into clipboard. This would be the most convenient I think as many people would then paste it into their long storage (notion, obsidian, zettelkasten, roam... (other than onenote or evernote or gdocs)
- Or download a markdown plain text file.

**Comment by dekart** [comment]
Exporting notes as a text file with Markdown markup would be awesome indeed!

**Comment by shuowu** [comment]
Export markdown file is supported in v1.6.0 (https://github.com/shuowu/yi-note/releases/tag/1.6.0). The new version has been submitted to chrome web store for review, it will be available and auto-upgrade in chrome in the next few hours. 

Close this issue for now.
