### ISSUE TITLE
Embed Screenshot on Google Docs Instead of Hyperlinking It

### ISSUE THREAD

**Issue by Faris999** [shuowu/yi-note#60]
When I export to Google Docs, the screenshots are uploaded into a separate folder and linked to Google Docs. It would've been better if the screenshots are embedded directly in the document. Alternatively, there could've been an option to choose whether or not the image will be embedded.

**Comment by shuowu** [comment]
I was planning to implement as what you described in this issue. But failed to find proper google docs api for that.. 

As the generated doc is still editable, you can add the screenshots manually if needed.

**Comment by Faris999** [comment]
How about [this](https://developers.google.com/docs/api/how-tos/images)? Can it help?

**Comment by shuowu** [comment]
I remember I did some investigation on this page. iirc, google drive cannot be used as a cdn to serve images, and there is no public api to support inserting base64 encoded image. So I don't see an easy way to get the image inserted into the doc.

It should be doable after proper cloud support.
