### ISSUE TITLE
Could you please add“ bilibili.com" and "https://open.163.com/" to the supported player?

### ISSUE THREAD

**Issue by zzxbisheng** [shuowu/yi-note#61]
Could you please add“ bilibili.com" and "https://open.163.com/" to the supported player?
Here is the introduction:https://en.wikipedia.org/wiki/Bilibili
BiliBili is a very popular video website in China, with many users using it.
There are a lot of people in China who want to take notes on videos of these two websites with our Yi-note plug-in, even if we needs to buy VIP!
Thanks a lot!

**Comment by shuowu** [comment]
I did some quick test on both sites, looks like they are both supported by current version of YiNote(1.5.3).
Can you share the specific video/url that not work?

**Comment by zzxbisheng** [comment]
I was negligent, the problem has been solved, thank you!
