### ISSUE TITLE
add on is not available on firefox store 

### ISSUE THREAD

**Issue by liutiming** [shuowu/yi-note#69]
hi thank you for this awesome add-on!

currently add on is not available on firefox store :( 

https://addons.mozilla.org/en-CA/firefox/addon/yinote/

**Comment by shuowu** [comment]
Thanks for reporting the issue! I’ll republish it on firefox store soon.

**Comment by liutiming** [comment]
sadly still not available. is there anything i can do to help?

**Comment by shuowu** [comment]
@liutiming Thanks for pinging me on the issue! 
should be available now. https://addons.mozilla.org/en-US/firefox/addon/yinote/

**Comment by liutiming** [comment]
thank you!
