### ISSUE TITLE
Support export to Notion

### ISSUE THREAD

**Issue by Benature** [shuowu/yi-note#7]
Can the note be exported to Notion(<https://www.notion.so>) too?

Notion is another powerful note app like EverNote.

**Comment by shuowu** [comment]
https://www.notion.so/Does-Notion-have-an-API-I-can-use-4541b07a5caa46dba0026624646118c0

Looks like they had plan to open developer api two years ago, but still not there yet. Please reopen this issue when Notion's developer api available.
