### ISSUE TITLE
Markdown Export Creating HTML Files, Not Markdown

### ISSUE THREAD

**Issue by golflabel** [shuowu/yi-note#84]
**Bug description**
"Export Markdown" option exports HTML instead of Markdown.

**To Reproduce**
1. Click "Export Markdown" option.

**Expected behavior**
A properly Markdown-formatted file would be saved.

**Screenshots**
After taking notes on any given video in YiNote, I click here:
<img width="338" alt="ScreenShot 2021-02-08 at 12 31 55@2x" src="https://user-images.githubusercontent.com/57685083/107271737-dffbc080-6a09-11eb-9dd3-962861e6790e.png">

Then my .md file looks like this:
<img width="667" alt="ScreenShot 2021-02-08 at 12 34 02@2x" src="https://user-images.githubusercontent.com/57685083/107271780-f144cd00-6a09-11eb-880c-035d873ffe5c.png">

The css styling and clickable links contained in the source text are now missing when rendering a Markdown preview:
<img width="668" alt="ScreenShot 2021-02-08 at 12 35 12@2x" src="https://user-images.githubusercontent.com/57685083/107271885-1afdf400-6a0a-11eb-8f24-7ab4f16dff6b.png">

**Browser**
- Chrome
- Version 88.0.4324.150 (Official Build) (x86_64)

**Additional context**
- I'm using an iMac on macOS Catalina
- I posted in another forum assuming it my lack of Markdown knowledge, but several people confirmed that the document was in HTML, not Markdown.

**Comment by sebastian-muthwill** [comment]
It seems that in version v1.6.0 in the Chrome extension the behavior is slightly different. Here the exported markdown file doesn´t contain the `<p>` tags but still has commented out the time stamp links. 

## current behavior

```<!-- Generated by <a href="https://www.yinote.co/#installation">YiNote</a> -->

<!-- # [5 steps to study with Obsidian and how I use it for exam revision using NeuraCache and Anki](https://www.youtube.com/watch?v=Bf3d7qyz17c) -->

<!-- ## [4:57](https://www.youtube.com/watch?v=Bf3d7qyz17c&t=297) -->

Notizen als Bulletpoints erstellen und mit Screenshots und weiteren Daten anreichern.
```

this causes markdown preview to threat this as a comment, and it will not be shown. 


## proposed solution

removing the comment part ```<!-- -->```from the markdown export
