### ISSUE TITLE
Support for markdown copy

### ISSUE THREAD

**Issue by kashyapmanu** [shuowu/yi-note#94]
Is it possible to add an option of COPY MARKDOWN TO CLIPBOARD along with DOWNLOAD MARKDOWN FILE?

I tried to do it myself but could not understand much. I am still learning. Sorry for the inconvenience.

**Comment by jarodise** [comment]
yes, would love have this feature too, copy and paste directly to note-taking tools like Obsidian or logseq.

**Comment by goxum** [comment]
I'd like to see this as well for the Notion note taking app. If I manually copy the text content of the downloaded .md file, thumbnails are gone by the way.
